#!/bin/sh
# Deployment need the following to be installed
# Applicatioons:
# - python3
# - pip3
# Pip libraries:
# - pyyaml
# - pyinstaller
pyinstaller --onefile --additional-hooks-dir=hooks amproxy.py
yes | cp dist/amproxy /usr/local/bin/
