---
services:

### NON ITERABLE CONTAINER BLOCK ###
# put your non iterable container here, use 4 spaces as indentation

### ITERABLE CONTAINER BLOCK ###
    ${app}-${no}:
        container_name: ${app}-${no}
        restart: always
        env_file: my.env
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ./www/invoices:/var/www/invoices
            - ./www/receipts:/var/www/receipts
            - ./www/outgoing_mail_attachments:/var/www/outgoing_mail_attachments
            - ./www/tmp_mail_attachments:/var/www/tmp_mail_attachments
    ${app}-2:
        image: areesmoon/submit-confbay1
        container_name: ${app}-2
        restart: always
        env_file: my.env
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ./www/invoices:/var/www/invoices
            - ./www/receipts:/var/www/receipts
            - ./www/outgoing_mail_attachments:/var/www/outgoing_mail_attachments
            - ./www/tmp_mail_attachments:/var/www/tmp_mail_attachments